---
#
# Tasks to be applied to all servers
#

- name: Check connectivity
  ansible.builtin.ping:
    data: alive
  tags: check

# Add further tasks for the common role (applied to all servers) to this playbook...

- name: Wheresalice specific setup
  ansible.builtin.include_tasks: wheresalice.yml

- name: Install common packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - rsync
      - rsyslog
      - vim
