---
- name: Ensure user is present.
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    shell: /bin/bash
    groups: "{{ item.groups }}"
    append: true
  with_items: "{{ wheresalice_users }}"

- name: Set authorized key took from file
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"
  with_items: "{{ wheresalice_users }}"

- name: Allow passwordless sudo
  community.general.sudoers:
    name: adm-passwordless
    group: adm
    nopassword: true
    commands: ALL
