name: ansible-lint
on: [pull_request]

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run:  |
          ansible-galaxy install -f -r requirements.yml
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24.6.0
